### DISCUSSION TITLE
How to execute Automation based on mower activity

### DISCUSSION THREAD

**Discussion by Stoufiler** [Thomas55555/husqvarna_automower#349] [Q&A]
Hello !

I'm trying to find how can I execute an automation when lawn mower change state from **MOWING** to **GOING_HOME** and from **GOING_HOME** to **PARKED_IN_CS**

How can I do that ?

I've tried this but it doesn't work : 

```yaml
platform: state
entity_id:
  - vacuum.lawn_mower
attribute: action
from: MOWING
to: GOING_HOME
```
