### ISSUE TITLE
YAML file /config/custom_components/husqvarna_automower/services.yaml contains duplicate key "default". Check lines 115 and 116

### ISSUE THREAD

**Issue by kalhimeo** [Thomas55555/husqvarna_automower#142]
There is a small typo in services.yaml

```
sunday:
      name: Sunday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      **default: false**
      **default: true**
      selector:
        boolean:
```

Easy fix ;-)
