### ISSUE TITLE
Question to use number_entity for park and start

### ISSUE THREAD

**Issue by Gloomyeye** [Thomas55555/husqvarna_automower#282]
Hello,

I have a question regarding the new usage of the number_entity for park and start. Could you give an example how to use this or update the usage section?

I use the current service for manually start the mower:
service: husqvarna_automower.park_and_start
data:
  command: Start
  duration: 60
target:
  entity_id: vacuum.husky

Thank you!

**Comment by Thomas55555** [comment]
Command would look like that:
```
service: number.set_value
data:
  value: '60'
target:
  entity_id: number.husky_mow_for
```
