### ISSUE TITLE
Token issue? 

### ISSUE THREAD

**Issue by XaviosTheBoss** [Thomas55555/husqvarna_automower#36]
Hello,

I'm using the version 2021.3.4 with Hacs. I'm able to use the integration and control my robot during 1 day. Then I have to restart home assistant to be able to control again the robot. Is it a token problem? I have no issue in logs.

Thank you.

**Comment by Thomas55555** [comment]
Hello,
that sounds relaly like a token isssue, because the token is valid for 24h. There was change in 2021.3.3 which refreshs the token instead of aksing for a new token every time the token expires. But in my tests I had no issuses.
Can you add the debug logging to your configuration.yaml and have a look what happens 24h after restart?
````
logger:
  default: info
  logs:
    custom_components.husqvarna_automower: debug
    custom_components.husqvarna_automower.vacuum: debug
    custom_components.husqvarna_automower.config_flow: debug
    aioautomower: debug
````
I will also release a new version soon, which completely changes the token managment. It would be good, if I could fix your issue before releasing it.
