### ISSUE TITLE
Every restart of HA needs re-authentification of integration

### ISSUE THREAD

**Issue by TPochobradsky** [Thomas55555/husqvarna_automower#62]
Hello, thank you for good job. Could you tell me what i do wrong? When I restart of HA The Husqvarna Automower integration needs to re-authenticate with Husqvarna. Thank you for answer
Tomas

**Comment by Thomas55555** [comment]
Hello,
can you paste, the config entries (in CONFIG_Directory/.storage/core.config_entries) before the restart here? it should look like that:

```
                "entry_id": "aa5762d5503e7071fd5b8e652ede8646",
                "version": 2,
                "domain": "husqvarna_automower",
                "title": "bb861923-6786-4f70-b930-1fc4a24107b9",
                "data": {
                    "token": {
                        "access_token": "eyJhb[]ik7fNC1og",
                        "scope": "iam:read",
                        "expires_in": 86399,
                        "refresh_token": "da197495-58c1-4299-a834-xxxxxxx",
                        "provider": "husqvarna",
                        "user_id": "5a93141e-55a7-479f-xxxx-8a63188c054f",
                        "token_type": "Bearer",
                        "expires_at": 1621182137.2122638,
                        "status": 200
```
Please modify the access_token and the refresh_token in github, because of security reasons.
Add the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.husqvarna_automower: debug
    custom_components.husqvarna_automower.vacuum: debug
    custom_components.husqvarna_automower.config_flow: debug
    aioautomower: debug
```
The restart and paste the config entries, too.
And post the relevant logfiles.
